version: "3.1"

services:

  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - 9200:9200
    networks:
      - elk

  logstash:
    image: kharmajbird/logstash:2.4
    secrets:
      - logstash_conf
    networks:
      - proxy
      - elk
    environment:
      - LOGSPOUT=ignore
    command: 'logstash -f /conf/logstash.conf'

  kibana:
    image: kibana:4.6
    networks:
      - proxy
      - elk
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    labels:
     - "com.df.notify=true"
     - "com.df.distribute=true"
     - "com.df.servicePath=/app/kibana,/bundles,/elasticsearch"
     - "com.df.port=5601"

networks:
  proxy:
    external: true
  elk:
    external: true
