version: "3"

services:

  logspout:
    image: gliderlabs/logspout
    ports:
      - 51415:51415
    networks:
      - proxy
      - elk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SYSLOG_FORMAT=rfc3164
      - MODE=swarm

networks:
  proxy:
    external: true
  elk:
    external: true


#?# syslog://logstash:51415
