version: '3'

services:

  main:
    image: kharmajbird/python-demo${TAG}
    networks:
      - proxy
      - default
    ports:
      - 8000:8000
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=8000

networks:
  default:
    external: false
  proxy:
    external: true
