version: "3.1"

services:

  viz:
    image: dockersamples/visualizer
    ports:
      - 8088:8088
    networks:
      - default
      - proxy
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
    labels:
      - "com.df.notify=true"
      - "com.df.distribute=true"
#      - "com.df.servicePath=/"
#      - "com.df.reqPathSearch=/viz/app"
#      - "com.df.reqPathReplace=/*"
      - "com.df.port=8088"
    environment:
      - CTX_ROOT=/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: false
  proxy:
    external: true
