version: "3.1"

services:

  viz:
    image: dockersamples/visualizer
##    ports:
##      - 8080:8080
    networks:
      - default
      - proxy
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
    labels:
      - "com.df.notify=true"
      - "com.df.distribute=true"
      - "com.df.servicePath=/viz"
      - "com.df.port=8080"
    environment:
      - CTX_ROOT=viz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: false
  proxy:
    external: true
