version: '3'

services:

  main:
    image: kharmajbird/go-demo${TAG}
    environment:
      - DB=db
#      - DB=go-demo_db
    networks:
      - proxy
      - go-demo
      - default
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/demo
        - com.df.port=8080
      placement:
        constraints: [node.labels.nonlogger == true]

  db:
    image: mongo
    networks:
      - proxy
      - go-demo
      - default

networks:
  default:
    external: false
  proxy:
    external: true
  go-demo:
    external: true
