version: '3'

services:

  main:
    image: kharmajbird/go-demo${TAG}
    environment:
      - DB="go-demo-db-rs1,go-demo-db-rs2,go-demo-db-rs3"
#      - DB="go-demo-db-rs1"
    networks:
      - proxy
      - default
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/demo
        - com.df.port=8080
      placement:
        constraints: [node.labels.nonlogger == true]

  go-demo-db-rs1:
    image: mongo:3.2.10
    networks:
      - default
    deploy:
      placement:
        constraints: [node.labels.nonlogger == true]
    command: 'mongod --replSet rs0'

  go-demo-db-rs2:
    image: mongo:3.2.10
    networks:
      - default
    deploy:
      placement:
        constraints: [node.labels.nonlogger == true]
    command: 'mongod --replSet rs0'

  go-demo-db-rs3:
    image: mongo:3.2.10
    networks:
      - default
    deploy:
      placement:
        constraints: [node.labels.nonlogger == true]
    command: 'mongod --replSet rs0'

  go-demo-db-init:
    image: kharmajbird/mongo${TAG}
    networks:
      - default
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [node.labels.nonlogger == true]
    command: '/init-mongo-rs.sh go-demo-db-rs1 go-demo-db-rs2 go-demo-db-rs3'

networks:
  default:
    external: false
  proxy:
    external: true
