version: "3.1"

services:

  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - 9200:9200
    networks:
      - elk
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.logger == true]
    volumes:
      - elasticsearch_db:/usr/share/elasticsearch/data

  logstash:
    image: kharmajbird/logstash
    ports:
      - 5000:5000
    networks:
      - proxy
      - elk
    environment:
      - LOGSPOUT=ignore
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.logger == true]

  kibana:
    image: kibana:4.6
    ports:
      - 5601:5601
    networks:
      - proxy
      - elk
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.logger == true]
    labels:
     - "com.df.notify=true"
     - "com.df.distribute=true"
     - "com.df.servicePath=/app/kibana,/bundles,/elasticsearch"
     - "com.df.port=5601"

networks:
  proxy:
    external: true
  elk:
    external: true

volumes:
  elasticsearch_db:
