version: "3.1"

services:

  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - 9200:9200
    networks:
      - elk
    deploy:
      placement:
        constraints: [node.labels.logger == true]
      resources:
        limits:
          memory: 1g
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_db1:/usr/share/elasticsearch/data

  elasticsearch2:
    image: elasticsearch:2.4
    networks:
      - elk
    deploy:
      placement:
        constraints: [node.labels.logger == true]
      resources:
        limits:
          memory: 1g
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_db2:/usr/share/elasticsearch/data

  logstash:
    image: kharmajbird/logstash
    ports:
      - 5000:5000
    networks:
      - proxy
      - elk
    environment:
      - LOGSPOUT=ignore
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.logger == true]
    depends_on:
        - elasticsearch
        - elasticsearch2

  logspout:
    image: gliderlabs/logspout
    ports:
      - 51415:51415
    networks:
      - proxy
      - elk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SYSLOG_FORMAT=rfc3164
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s
    depends_on:
      - logstash
    command: 'syslog://logstash:51415'

  kibana:
    image: kibana:4.6
    ports:
      - 5601:5601
    networks:
      - proxy
      - elk
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.logger == true]
    labels:
     - "com.df.notify=true"
     - "com.df.distribute=true"
     - "com.df.servicePath=/app/kibana,/bundles,/elasticsearch"
     - "com.df.port=5601"
    depends_on:
        - logstash
        - elasticsearch
        - elasticsearch2
        - logspout

networks:
  proxy:
    external: true
  elk:
    external: true

volumes:
  elasticsearch_db1:
    driver: local
  elasticsearch_db2:
    driver: local
