version: '3'

services:

  main:
    image: kharmajbird/meany${TAG}
    environment:
      - DB=db
    networks:
      - proxy
      - default
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=8080
##      placement:
##        constraints: [node.labels.nonlogger == true]

  db:
    image: mongo
    networks:
      - default

networks:
  default:
    external: false
  proxy:
    external: true
